volumes:
  stretch-data:
    external: true
services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi/app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
  database:
    image: postgres:14.2-bullseye
    volumes:
      - stretch-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=accounts,classes,levels
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
  accounts-api:
    build:
      context: ./accounts/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8100:8000"
    volumes:
      - ./accounts/api:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://accounts:password@database:5432/accounts
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
      PEXELS_API_KEY: ${PEXELS_API_KEY}
      DJWTO_SIGNING_KEY: ${DJWTO_SIGNING_KEY}
  classes-api:
    build:
      context: ./classes/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./classes/api:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://classes:password@database:5432/classes
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
      PEXELS_API_KEY: ${PEXELS_API_KEY}
      DJWTO_SIGNING_KEY: ${DJWTO_SIGNING_KEY}
  levels-api:
    build:
      context: ./levels/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./levels/api:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://levels:password@database:5432/levels
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
      PEXELS_API_KEY: ${PEXELS_API_KEY}
      DJWTO_SIGNING_KEY: ${DJWTO_SIGNING_KEY}
  
